# ----------------------------------------
# TNT矿车伤害设置
# ----------------------------------------
# 允许TNT矿车对玩家造成的最大最终伤害（扣除护甲后的实际扣血量）
# 2.0 = 1颗心，16.0 = 8颗心，20.0 = 10颗心(秒杀无甲)
max-tnt-minecart-damage: 16.0

# ----------------------------------------
# 烟花弩伤害设置
# ----------------------------------------
firework:
  # 含有1个烟火之星时的基础伤害 (1.0 = 半颗心)
  base-damage: 10.0
  # 每多塞入一个烟火之星，额外增加的伤害
  # 例如 7个星的总伤害 = 10.0 + (6 * 5.0) = 40.0 (秒杀无甲玩家)
  damage-per-star: 2.0

# ----------------------------------------
# 经验掉落设置
# ----------------------------------------
exp:
  # 怪物掉落经验倍率
  # 1.0 = 原版经验 (100%)
  # 2.0 = 双倍经验 (200%)
  # 0.5 = 经验减半 (50%)
  monster-multiplier: 2.0

# ----------------------------------------
# 食物食用冷却设置
# ----------------------------------------
food-cooldown:
  # 尝试在冷却期间再次食用时的提示消息 (& 为颜色代码)
  cooldown-message: "&c你吃得太快了，请稍后再试"
  # 通过 item_name 原始文本匹配物品，并设置冷却时间 (单位: ticks, 20 ticks = 1 秒)
  items:
    群英荟萃: 20
    速食金苹果: 20

# ----------------------------------------
# 瞬间治疗药水对亡灵生物设置
# ----------------------------------------
instant-heal-undead:
  # 瞬间治疗 I / II 级基础伤害 (会按飞溅命中强度缩放)
  damage-level-1: 6.0
  damage-level-2: 12.0
  slowness:
    duration-ticks: 100
    amplifier: 3
  weakness:
    duration-ticks: 100
    amplifier: 3

# ----------------------------------------
# 手持地图队友发光设置
# ----------------------------------------
team-map-glow:
  # 触发发光效果的主手/副手物品材质
  materials:
    - COMPASS

# ----------------------------------------
# 盘丝效果强化及酿造设置
# ----------------------------------------
weaving-buff:
  # 酿造出的盘丝药水持续时间 (单位: Tick, 20 Tick = 1 秒)
  # 原版默认是 3600 (3分钟)。此处修改为 1200 (1分钟)
  duration-ticks: 1200
  # 处于蜘蛛网中下落时的速度 (负数, 越小掉得越快)
  fall-speed: -0.4
  # 处于蜘蛛网中时的水平移动推进力 (正数, 越大走得越快)
  horizontal-boost: 0.3
